version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: microlib-mysql
    ports:
    - "3306:3306"
    volumes:
      - ./dbdata/mysql:/var/lib/mysql
      - ./dbdata/my_cnf:/etc/my.cnf
    environment:
      MYSQL_DATABASE: "microlib"
      MYSQL_ROOT_PASSWORD: "microlib123"
      MYSQL_USER: "dev1"
      MYSQL_PASSWORD: "microlib123"
    restart: always
