version: '3'
services:
  microlib-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microlib-server
    ports:
      - "8081:8081"
    volumes:
      - ./jar:/src
    working_dir: /src
    depends_on:
      - microlib-mysql
    command: ["../app/wait-for-it.sh", "microlib-mysql:3306", "--", "java", "-Dcom.sun.management.jmxremote", "-Xmx128m", "-jar", "microlib-0.1-all.jar"]

  microlib-mysql:
    image: mysql:5.7
    container_name: microlib-mysql
    ports:
    - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "microlib123"
#      MYSQL_USER: "dev1"
#      MYSQL_PASSWORD: "microlib123"
    restart: always

  microlib-client:
    build:
      context: .
      dockerfile: Dockerfile-Client
    container_name: microlib-client
    ports:
      - "8080:8080"
