version: '3'
services:
#  microlib-server:
#    build:
#      context: .
#      dockerfile: Docker/Dockerfile
#    container_name: microlib-server
#    ports:
#      - "8081:8081"
#    volumes:
#      - ./jar:/app
#    working_dir: /app
#    depends_on:
#      - microlib-mysql
#    command: ["./wait-for-it.sh", "microlib-mysql:3306", "--", "java", "-Dcom.sun.management.jmxremote", "-Xmx128m", "-jar", "microlib-0.1-all.jar"]

  microlib-mysql:
    image: mysql:5.7
    container_name: microlib-mysql
    ports:
    - "3306:3306"
    volumes:
      - ./Docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "microlib123"
#      MYSQL_USER: "dev1"
#      MYSQL_PASSWORD: "microlib123"
    restart: always

  microlib-client:
    build:
      context: .
      dockerfile: microlib-client/Docker/Dockerfile-Client
    container_name: microlib-client
    ports:
      - "8080:8080"
