# micronautの設定
micronaut:
  application:
    name: microlib
  server:
    context-path: microlib

# DB接続の設定
datasources:
  default:
    url: jdbc:mysql://localhost:3306/microlib?characterEncoding=utf8&useSSL=true
    #      url: jdbc:mysql://mysql:3306/mtmtodo?characterEncoding=utf8&useSSL=true
    username: dev1
    password: microlib123
    driverClassName: com.mysql.cj.jdbc.Driver

# JPAの設定
jpa:
  default:
    packages-to-scan:
      - 'com.xavier.microlib.model'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
