# micronautの設定
micronaut:
  application:
    name: microlib
  server:
    context-path: microlib
    port: 8081
    # オリジン間リソース共有を許可
    cors:
      enabled: true

# DB接続の設定
datasources:
  default:
    url: jdbc:h2:mem:microlib-test
    driverClassName: org.h2.Driver
    username: microlib
    password: microlib
    schema-generate: CREATE_DROP
    dialect: H2

# JPAの設定
jpa:
  default:
    packages-to-scan:
      - 'com.xavier.microlib.domain'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

# jacksonの設定
jackson:
  json-view:
    enabled: true

# 表紙画像ディレクトリ
microlib:
  book:
    cover:
      directory: /dev/microlib/image